### ISSUE TITLE
Grid column count is not stable

### ISSUE THREAD

**Issue by ilkkao** [benhowell/react-grid-gallery#84] opened 2018-07-31 07:28 UTC
### Expected behaviour

More columns appear when the viewport gets wider (1,2,3).

### Actual behaviour

Column count flickers when the viewport gets wider (1,2,1,2,1,2,1,2,3,4,5).

### Steps to reproduce behaviour

1. Open chrome devtools
2. Go to https://riistakamera.ilkka.xyz/
3. Enable mobile view
4. Select "responsive" mode
5. Change the viewport width slowly from 300 to 500 pixels using the bar on the right

This is an issue as some phone models show one column even there is room for two columns (and phones with smaller screen show two columns).

I can fix this with CSS media queries that set the container width to some fixed values but wanted to open an issue first to check if this is not expected behaviour. Feels like a rounding error. 

### Operating system

MacOS

### Browser and version

Desktop Google Chrome

**Comment by benhowell** [comment] 2018-07-31 23:01
Thanks @ilkkao, it's not expected behaviour. You could be right, it sounds like a rounding error, most likely to do with how the row width is calculated. I've been able to reproduce the same flickering effect with the demo as well.

I'll look into it.

**Comment by itoldya** [comment] 2022-08-07 19:56
Hello @ilkkao! Thank you for the bug report. 

Looks like your demo site is no longer available. I managed to reproduce mentioned behavior by assigning decimal value to container width - https://github.com/benhowell/react-grid-gallery/pull/170/files. 

And yes it is a rounding error. Fix will be available soon.

**Comment by itoldya** [comment] 2022-08-23 10:36
Fixed in https://github.com/benhowell/react-grid-gallery/releases/tag/v0.5.6

**Closed by itoldya** 2022-08-23 10:36 UTC
