### ISSUE TITLE
Lightbox image size

### ISSUE THREAD

**Issue by brianrc** [benhowell/react-grid-gallery#15] opened 2016-12-21 02:54 UTC
Can we have a prop to control the lightbox image size? React-images lets you pass in a width prop.

**Comment by benhowell** [comment] 2016-12-21 06:56
Hi Brian, I added a new prop called `lightboxWidth`. Pass it to the `<Gallery>` tag.

**Comment by brianrc** [comment] 2017-01-13 07:21
Thank you. Finally got around to updating my project to v0.2.9 and trying out the new prop, but it doesn't seem to have an effect. Not sure why.

**Comment by benhowell** [comment] 2017-01-13 07:35
Ah, stuffed up. Should be all good now ;-)

**Comment by brianrc** [comment] 2017-01-13 21:40
Updated to v0.2.10, but it's still not working. :(

**Comment by benhowell** [comment] 2017-01-13 21:41
What error are you getting?

**Comment by benhowell** [comment] 2017-01-13 22:05
Fixed by afc0492af6479e6a4dafa1560116cc3b1a5d2c4c

**Closed by benhowell** 2017-01-13 22:05 UTC

**Comment by brianrc** [comment] 2017-01-13 22:13
No errors. Cache is cleared. Tried it in Chrome and Firefox.

https://github.com/brianrc/acrobrian/commit/59a05579bcc6997ce52d16e5fdb9b2ad7437a7e8

**Comment by brianrc** [comment] 2017-01-13 22:42
Temp live site. http://mathematician-status-20032.netlify.com/

**Comment by benhowell** [comment] 2017-01-13 22:52
It seems my monitor isn't big enough to display any of your photos at
1536px wide! (due to the height of your photos).
I'll try a short wide photo and see what's going on...

**Comment by benhowell** [comment] 2017-01-13 23:10
Ok, I can confirm that the prop _is_ passed correctly and works for any width up to and including 1024. This appears to be a bug in https://github.com/jossmac/react-images so I'm going to submit this issue upstream to @jossmac

**Comment by benhowell** [comment] 2017-01-13 23:48
Finally! I inadvertently missed a release of react-images. Updated 0.4.11 -> 0.5.2 and all is good now.

You can see it in action here (see the Pre-selected images demo):
https://benhowell.github.io/react-grid-gallery/

Note: the only photo that exceeds 1024 is "Red zone, Paris"

**Comment by brianrc** [comment] 2017-01-18 06:20
Thank you. It's working great now!
