### ISSUE TITLE
Even 'Click' is not available

### ISSUE THREAD

**Issue by suruirui** [benhowell/react-grid-gallery#130] opened 2019-11-08 10:33 UTC
### Expected behaviour
click a single image in the grid
### Actual behaviour
``````````````````````````````````````````````the console output ```````````````````````````````````````
react-dom.development.js:545 Warning: Expected `onClick` listener to be a function, instead got `false`.

If you used to conditionally omit it with onClick={condition && value}, pass onClick={condition ? value : undefined} instead.
    in div (created by Container)
    in Container (created by Lightbox)
    in Transition (created by CSSTransition)
    in CSSTransition
    in div (created by TransitionGroup)
    in TransitionGroup
    in div
    in PassContext
warningWithoutStack @ react-dom.development.js:545
warning @ react-dom.development.js:2853
warnForInvalidEventListener @ react-dom.development.js:8659
setInitialDOMProperties @ react-dom.development.js:8747
setInitialProperties @ react-dom.development.js:8931
finalizeInitialChildren @ react-dom.development.js:9955
completeWork @ react-dom.development.js:19105
completeUnitOfWork @ react-dom.development.js:22241
performUnitOfWork @ react-dom.development.js:22218
workLoopSync @ react-dom.development.js:22185
renderRoot @ react-dom.development.js:21878
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
discreteUpdates$1 @ react-dom.development.js:21677
discreteUpdates @ react-dom.development.js:2359
dispatchDiscreteEvent @ react-dom.development.js:5979
react-dom.development.js:545 Warning: Expected `onTouchEnd` listener to be a function, instead got `false`.

If you used to conditionally omit it with onTouchEnd={condition && value}, pass onTouchEnd={condition ? value : undefined} instead.
    in div (created by Container)
    in Container (created by Lightbox)
    in Transition (created by CSSTransition)
    in CSSTransition
    in div (created by TransitionGroup)
    in TransitionGroup
    in div
    in PassContext
warningWithoutStack @ react-dom.development.js:545
warning @ react-dom.development.js:2853
warnForInvalidEventListener @ react-dom.development.js:8659
setInitialDOMProperties @ react-dom.development.js:8747
setInitialProperties @ react-dom.development.js:8931
finalizeInitialChildren @ react-dom.development.js:9955
completeWork @ react-dom.development.js:19105
completeUnitOfWork @ react-dom.development.js:22241
performUnitOfWork @ react-dom.development.js:22218
workLoopSync @ react-dom.development.js:22185
renderRoot @ react-dom.development.js:21878
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
discreteUpdates$1 @ react-dom.development.js:21677
discreteUpdates @ react-dom.development.js:2359
dispatchDiscreteEvent @ react-dom.development.js:5979
react-dom.development.js:11494 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: PaginatedThumbnails
### Operating system
win10 home 
### Browser and version
chrome v78.0.3904.87
### Hardware
Dell Desktop

**Comment by icorradi** [comment] 2020-02-28 01:19
+1

**Comment by Mr-Usman** [comment] 2020-10-31 07:04
+1

**Comment by hellolingxh** [comment] 2021-10-16 17:41
+1

**Comment by itoldya** [comment] 2022-08-27 07:50
Hello, guys thanks for reporting!

It's a known bug that occurs if you are using React 17 and higher. The root of the problem is in the [`react-images`](https://github.com/jossmac/react-images) - library we are using for the lightbox component. 

We started a discussion to find a way to fix it. Most probably we will cut lightbox functionality at all. Please join [this discussion](https://github.com/benhowell/react-grid-gallery/discussions/179) your feedback is highly appreciated!

**Comment by itoldya** [comment] 2022-09-18 16:12
Lightbox was stripped out in the v1.0.0 so I close the issue because it's not actual anymore

**Closed by itoldya** 2022-09-18 16:12 UTC
